import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <header>header</header>
        <h1 className=''>Hello world</h1>
      </main>
      <footer className=''>ltda</footer>
    </div>
  )
}

export default Home
